version: 1.0.{build}
configuration: Release
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
cache: '%USERPROFILE%\.nuget\packages'
build_script:
- ps: '& ./build.ps1'
test: off
artifacts:
- path: artifacts\**\*.*
deploy:
- provider: NuGet
  api_key:
    secure: MKJFwv0jwKlFm07R0ToinHoLs3g8z0oCjC1pAj48ISSxEWIZ4wGI30AZqOrkMcVc
  skip_symbols: true